baseURL: https://jacob.millward.dev/
languageCode: en-gb
title: Jacob Millward
theme: PaperModX

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - name: Archive
      url: archive/
      weight: 1
    - name: Search
      url: search/
      weight: 2

taxonomies:
  tag: tags

pygmentsUseClasses: true

params:
  defaultTheme: auto
  hideFooter: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  TocOpen: true
  TocSide: left

  description: Personal internet resting place of Jacob Millward. Software Developer, technologist, keen drinker of tea.
  author: Jacob Millward
  Email: jacob@millward.dev

  homeInfoParams:
    title: Jacob Millward
    content: >
      I’m a developer in the north of England, with a habit of breaking warranties.


      You can find write ups of my ~~fumblings~~ amazing successes below.
      Alternatively check out my work on GitHub.


      Want to hire me? Get in touch.

  socialIcons: # optional
    - name: "github-simple"
      url: "https://github.com/JacobMillward"
    - name: "linkedin-simple"
      url: "https://linkedin.com/in/JacobMillward"
    - name: "mdi-email"
      url: email
    - name: rss-simple
      url: "index.xml"

  analytics:
    google:
      siteVerificationTag: 1YR2u6Z_bXVs7nOG7Ox_meL7CGKhwLS2sd3u8IDLPCk
