baseURL: https://jacob.millward.dev/
languageCode: en-gb
title: Jacob Millward
theme: PaperMod

outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - name: Archive
      url: archive/
      weight: 1
    - name: Tags
      url: tags/
      weight: 2
    - name: Search
      url: search/
      weight: 3

taxonomies:
  tag: tags

params:
  defaultTheme: auto
  hideFooter: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  description: Personal internet resting place of Jacob Millward. Software Developer, technologist, keen drinker of tea.
  author: Jacob Millward

  homeInfoParams:
    title: Jacob Millward
    content: >
      I’m a developer in the north of England, with a habit of breaking warranties.


      You can find write ups of my ~~fumblings~~ amazing successes below.
      Alternatively check out my work on GitHub.


      Want to hire me? Get in touch.

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/JacobMillward"
    - name: "email"
      url: "mailto:jacob@millward.dev"
    - name: "linkedin"
      url: "https://linkedin.com/in/JacobMillward"
    - name: Rss
      url: "index.xml"

  analytics:
    google:
      siteVerificationTag: 1YR2u6Z_bXVs7nOG7Ox_meL7CGKhwLS2sd3u8IDLPCk